[package]
edition = "2021"
name = "zkp"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
bellman = "0.11.1"
bls12_381 = "0.6.0"
ff = "0.11.0"
pairing = "0.21.0"
rand = "0.8.5"
sha2 = "0.10.2"
